// Generated by https://quicktype.io

export interface IAPIResponse {
	pagination: Pagination;
	results:    Result[];
}

export interface Pagination {
	pageSize: number;
	page:     number;
	total:    number;
}

export interface Result {
	_id:      string;
	stations: Station[];
}

export interface Station {
	indexes:      Index[];
	measurements: Measurement[];
	location:     Location;
	source_id:    SourceID;
	name:         string;
	id:           string;
}

export interface Index {
	calculationTime:      string;
	responsiblePollutant: string;
	value:                string;
	scale:                Scale;
}

export enum Scale {
	Imeca = "IMECA",
}

export interface Location {
	alt: string;
	lon: string;
	lat: string;
}

export interface Measurement {
	averagedOverInHours: string;
	time:                string;
	value:               string;
	unit:                Unit;
	pollutant:           Pollutant;
}

export enum Pollutant {
	Co = "CO",
	No2 = "NO2",
	O3 = "O3",
	Pm10 = "PM10",
	So2 = "SO2",
}

export enum Unit {
	Ppm = "ppm",
	ΜgM3 = "µg/m3",
}

export enum SourceID {
	Gdl = "GDL",
	Source = "source",
}
